export interface Reward {
    name: string,
    desc: string,
    loyaltyType: string,
    startDate: Date,
    endDate: Date,
    barcode: string,
    recordStatus: boolean,
    imgUrl: string,
}

export const MOCK_REWARDS: Reward[] = [
    {
        name: 'Reward 1',
        desc: 'Default description for rewards',
        imgUrl: 'https://uowplaybook.s3-ap-southeast-2.amazonaws.com/logo/logo-secondary.png',
        loyaltyType: 'voucher',
        startDate: new Date(2021, 0, 1),
        endDate: new Date(2021, 0, 1),
        recordStatus: false,
        barcode: '123456789',
    },
    {
        name: 'Reward 2',
        desc: 'Default description for rewards',
        imgUrl: 'https://uowplaybook.s3-ap-southeast-2.amazonaws.com/logo/logo-secondary.png',
        loyaltyType: 'voucher',
        startDate: new Date(2021, 11, 31),
        endDate: new Date(2021, 11, 31),
        recordStatus: true,
        barcode: '123456789',
    },
    {
        name: 'Reward 3',
        desc: 'Default description for rewards',
        imgUrl: 'https://uowplaybook.s3-ap-southeast-2.amazonaws.com/logo/logo-secondary.png',
        loyaltyType: 'voucher',
        startDate: new Date(2021, 11, 31),
        endDate: new Date(2021, 11, 31),
        recordStatus: true,
        barcode: '123456789',
    },
    {
        name: 'Reward 4',
        desc: 'Default description for rewards',
        imgUrl: 'https://uowplaybook.s3-ap-southeast-2.amazonaws.com/logo/logo-secondary.png',
        loyaltyType: 'voucher',
        startDate: new Date(2021, 11, 31),
        endDate: new Date(2021, 11, 31),
        recordStatus: true,
        barcode: '123456789',
    },
    {
        name: 'Reward 5',
        desc: 'Default description for rewards',
        imgUrl: 'https://uowplaybook.s3-ap-southeast-2.amazonaws.com/logo/logo-secondary.png',
        loyaltyType: 'voucher',
        startDate: new Date(2021, 11, 31),
        endDate: new Date(2021, 11, 31),
        recordStatus: true,
        barcode: '123456789',
    },
    {
        name: 'Reward 6',
        desc: 'Default description for rewards',
        imgUrl: 'https://uowplaybook.s3-ap-southeast-2.amazonaws.com/logo/logo-secondary.png',
        loyaltyType: 'voucher',
        startDate: new Date(2021, 11, 31),
        endDate: new Date(2021, 11, 31),
        recordStatus: true,
        barcode: '123456789',
    },
    {
        name: 'Reward 7',
        desc: 'Default description for rewards',
        imgUrl: 'https://uowplaybook.s3-ap-southeast-2.amazonaws.com/logo/logo-secondary.png',
        loyaltyType: 'voucher',
        startDate: new Date(2021, 11, 31),
        endDate: new Date(2021, 11, 31),
        recordStatus: true,
        barcode: '123456789',
    },
    {
        name: 'Reward 8',
        desc: 'Default description for rewards',
        imgUrl: 'https://uowplaybook.s3-ap-southeast-2.amazonaws.com/logo/logo-secondary.png',
        loyaltyType: 'voucher',
        startDate: new Date(2021, 11, 31),
        endDate: new Date(2021, 11, 31),
        recordStatus: true,
        barcode: '123456789',
    },
];
