export interface Event {
    name: string,
    desc: string,
    imgUrl: string,
    registerUrl: string,
    startDate: Date,
    endDate: Date,
    recordStatus: boolean,
}

export const MOCK_EVENTS: Event[] = [
    {
        name: 'Event 1',
        desc: 'Default description for events',
        imgUrl: 'https://uowplaybook.s3-ap-southeast-2.amazonaws.com/logo/logo-secondary.png',
        registerUrl: 'https://www.google.com',
        startDate: new Date(2021, 0, 1),
        endDate: new Date(2021, 0, 1),
        recordStatus: false,
    },
    {
        name: 'Event 2',
        desc: 'Default description for events',
        imgUrl: 'https://newinti.edu.my/wp-content/uploads/2017/12/INTI-Logo.jpg',
        registerUrl: 'https://www.google.com',
        startDate: new Date(2021, 11, 31),
        endDate: new Date(2021, 11, 31),
        recordStatus: true,
    },
    {
        name: 'Event 3',
        desc: 'Default description for events',
        imgUrl: 'https://newinti.edu.my/wp-content/uploads/2017/12/INTI-Logo.jpg',
        registerUrl: 'https://www.google.com',
        startDate: new Date(2021, 11, 31),
        endDate: new Date(2021, 11, 31),
        recordStatus: true,
    },
    {
        name: 'Event 4',
        desc: 'Default description for events',
        imgUrl: 'https://newinti.edu.my/wp-content/uploads/2017/12/INTI-Logo.jpg',
        registerUrl: 'https://www.google.com',
        startDate: new Date(2021, 11, 31),
        endDate: new Date(2021, 11, 31),
        recordStatus: true,
    },
    {
        name: 'Event 5',
        desc: 'Default description for events',
        imgUrl: 'https://newinti.edu.my/wp-content/uploads/2017/12/INTI-Logo.jpg',
        registerUrl: 'https://www.google.com',
        startDate: new Date(2021, 11, 31),
        endDate: new Date(2021, 11, 31),
        recordStatus: true,
    },
    {
        name: 'Event 6',
        desc: 'Default description for events',
        imgUrl: 'https://newinti.edu.my/wp-content/uploads/2017/12/INTI-Logo.jpg',
        registerUrl: 'https://www.google.com',
        startDate: new Date(2021, 11, 31),
        endDate: new Date(2021, 11, 31),
        recordStatus: true,
    },
    {
        name: 'Event 7',
        desc: 'Default description for events',
        imgUrl: 'https://newinti.edu.my/wp-content/uploads/2017/12/INTI-Logo.jpg',
        registerUrl: 'https://www.google.com',
        startDate: new Date(2021, 11, 31),
        endDate: new Date(2021, 11, 31),
        recordStatus: true,
    },
    {
        name: 'Event 8',
        desc: 'Default description for events',
        imgUrl: 'https://newinti.edu.my/wp-content/uploads/2017/12/INTI-Logo.jpg',
        registerUrl: 'https://www.google.com',
        startDate: new Date(2021, 11, 31),
        endDate: new Date(2021, 11, 31),
        recordStatus: true,
    },
    {
        name: 'Event 9',
        desc: 'Default description for events',
        imgUrl: 'https://newinti.edu.my/wp-content/uploads/2017/12/INTI-Logo.jpg',
        registerUrl: 'https://www.google.com',
        startDate: new Date(2021, 11, 31),
        endDate: new Date(2021, 11, 31),
        recordStatus: true,
    },
    {
        name: 'Event 10',
        desc: 'Default description for events',
        imgUrl: 'https://newinti.edu.my/wp-content/uploads/2017/12/INTI-Logo.jpg',
        registerUrl: 'https://www.google.com',
        startDate: new Date(2021, 11, 31),
        endDate: new Date(2021, 11, 31),
        recordStatus: true,
    },
];
